DjangoChessApi/Chess/urls.py
from django.urls import path

from DjangoChessApi.Chess import all_views as views
from DjangoChessApi.Chess.views.GameListView import GameListView
from DjangoChessApi.Chess.views.UserGameTypeListView import UserGameTypeListView
from DjangoChessApi.Chess.views.UserListView import UserListView


urlpatterns = [
    path('', views.home, name="home"),
    # Configurations
    path('configure/', views.create_configuration, name="configure"),
    path('configure/<int:game_type_id>/', views.configuration, name="configure-edit"),
    path(
        'configure/<int:game_type_id>/board',
        views.configuration_board,
        name="configure-board",
    ),
    # Playing
    path('game/create/', views.create_game, name="create-game"),
    path(
        'game/create/<int:game_type_id>/',
        views.create_game_redirect,
        name="create-game-redirect",
    ),
    path('game/join/<int:game_id>/', views.join_game, name="join-game"),
    path('game/play/<int:game_id>/', views.play_game, name="play-game"),
    path('games/', GameListView.as_view(), name="games"),
    path('users/', UserListView.as_view(), name="users"),
    path(
        'users/<int:user_id>/game_type/',
        UserGameTypeListView.as_view(),
        name="user_gametype",
    ),

    path('chat/', views.index, name='index'),
    path('chat/<str:room_name>/', views.room, name='room'),
]

app_name = 'Chess'

config/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('DjangoChessApi.Chess.urls', namespace='Chess')),
    path('api/', include('DjangoChessApi.api.urls')),
    path('admin/', admin.site.urls),
    path('grappelli/', include('grappelli.urls')),
    # Accounts
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
]

DjangoChessApi/Chess/models.py
# pylint: disable=E1136
# disabling E1136 so pylint doesn't yell about indexing json fields
import random
from enum import Enum

from django.contrib.auth.models import User
from django.db import models
from django.db.models.deletion import CASCADE, SET_NULL

from chess.chess_configurations import get_standard_chess_pieces


class VisibilityOptions(Enum):
    PRIVATE = "PR"
    FRIENDS = "FR"
    PUBLIC = "PU"
    STANDARD = "ST"

    @classmethod
    def all(cls):
        return [
            VisibilityOptions.PRIVATE,
            VisibilityOptions.FRIENDS,
            VisibilityOptions.PUBLIC,
            VisibilityOptions.STANDARD,
        ]


class GameType(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField()
    rules = models.JSONField(default=get_standard_chess_pieces)
    visibility = models.CharField(
        default=VisibilityOptions.PRIVATE.value,
        max_length=2,
        choices=[(tag.value, tag.name) for tag in VisibilityOptions.all()],
    )
    created_by = models.ForeignKey(User, null=True, on_delete=SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def rule_definitions(self):
        return self.rules['pieces']

    def get_rules(self):
        return self.rules

    def player_for_color(self, color):
        for player in self.rules['players'].keys():
            if player != 'current' and self.rules['players'][player]['color'] == color:
                return player
        return None

    def set_piece_location(self, player, piece_name, row, column):
        self.clear_location(row, column)
        self.rules['board'][player][piece_name].append(
            {'position': [row, column], 'move_count': 0}
        )

    def clear_location(self, row, column):
        for player in self.rules['board']:
            for piece in self.rules['board'][player]:
                for definition in self.rules['board'][player][piece]:
                    if definition['position'] == [row, column]:
                        self.rules['board'][player][piece].remove(definition)
                        return


class Game(models.Model):
    data = models.JSONField(
        default=get_standard_chess_pieces
    )  # is the data used by the chess library

    rule_name = models.CharField(max_length=30)
    rule_description = models.TextField()

    free_play = models.BooleanField(default=True)  # if set to true, don't enforce users for white/black

    history = models.JSONField(null=True)
    player1 = models.ForeignKey(
        User, null=True, on_delete=CASCADE, related_name='games_player1'
    )
    player2 = models.ForeignKey(
        User, null=True, on_delete=CASCADE, related_name='games_player2'
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def has_both_players(self):
        return self.player1 is not None and self.player2 is not None

    @property
    def ready_to_play(self):
        return self.free_play if self.free_play else self.has_both_players

    @property
    def rules(self):
        return self.data['pieces']

    @property
    def turn(self):
        return self.data['players']['current']

    def is_my_turn(self, user):
        if not self.ready_to_play:
            return False
        elif self.free_play:
            return True
        elif self.data['players']['current'] == 'Player 1':
            return user == self.player1
        else:
            return user == self.player2

    @property
    def turn_color(self):
        return self.data['players'][self.turn]['color']

    @property
    def rule_summary(self):
        return {'name': self.rule_name, 'description': self.rule_description}

    def set_player(self, user, color):
        if user.is_authenticated:
            if color == 'random':
                if random.choice([1, 2]) == 1:
                    self.player1 = user
                else:
                    self.player2 = user
            elif color == 'white' and self.player1 is None:
                self.player1 = user
            elif color == 'black' and self.player2 is None:
                self.player2 = user
            else:
                print("somehow don't know who to set??")

    def set_player2(self, user):
        if self.player1 is None and self.player2 != user:
            self.player1 = user
        elif self.player2 is None and self.player1 != user:
            self.player2 = user
        else:
            print("Setting second player but already set or existing player.")

DjangoChessApi/Chess/forms.py
from django.forms import ModelForm, Textarea

from .models import GameType


class GameTypeForm(ModelForm):
    class Meta:
        model = GameType
        fields = ['name', 'description']
        widgets = {
            'description': Textarea(attrs={'rows': 2, 'cols': 40}),
        }

DjangoChessApi/Chess/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

from chess.chess import Chess
from chess.chess_configurations import (
    get_capture_action_rules,
    get_movement_directions,
    get_movement_rules,
    get_post_move_actions_rules,
)
from rest_framework.reverse import reverse

from .forms import GameTypeForm
from .helpers import get_displayable_board, get_displayable_history, get_pieces
from .models import Game, GameType, VisibilityOptions


def home(request):
    standard_game_types = GameType.objects.filter(
        visibility=VisibilityOptions.STANDARD.value
    ).all()

    username = None
    if request.user.is_authenticated:
        username = request.user.username
        private_game_types = GameType.objects.filter(
            visibility=VisibilityOptions.PRIVATE.value, created_by=request.user
        ).all()
    else:
        private_game_types = []
    return render(
        request,
        'chess/main/home.html',
        {'game_types': private_game_types, 'standard_game_types': standard_game_types, 'username': username},
    )


def create_game(request):
    game_types = GameType.objects.all()
    return render(request, 'chess/main/create_game.html', {'game_types': game_types})


def create_game_redirect(_, game_type_id):
    game_type = GameType.objects.get(pk=game_type_id)
    new_game = Game(
        data=game_type.get_rules(),
        rule_name=game_type.name,
        rule_description=game_type.description,
    )
    new_game.save()
    url = reverse('Chess:play-game', kwargs={'game_id': new_game.id})
    return HttpResponseRedirect(url)


def play_game(request, game_id):
    game = Game.objects.get(pk=game_id)
    chess = Chess(game.data)
    displayable_board = get_displayable_board(chess.board)
    destinations_url = reverse('move-destinations', args=[game.id])
    move_url = reverse('move-move', args=[game.id])
    promote_url = reverse('move-promote', args=[game.id])

    promotion_pieces = get_pieces(game.data, ignore=['king', 'pawn'])

    history = get_displayable_history(chess)
    context = {
        'board': displayable_board,
        'destinations_url': destinations_url,
        'move_url': move_url,
        'promote_url': promote_url,
        'rule_summary': game.rule_summary,
        'turn': game.turn_color,
        'history': history,
        'id': game.id,
        'promotion_pieces': promotion_pieces,
    }
    return render(request, 'chess/main/play_game.html', context)


def create_configuration(request):
    if request.method == "POST":
        form = GameTypeForm(request.POST)
        if form.is_valid():
            game_type = form.save(commit=False)
            game_type.created_by = request.user
            game_type.save()
            return HttpResponseRedirect(
                reverse('Chess:configure-edit', kwargs={'game_type_id': game_type.id})
            )
    else:
        form = GameTypeForm()
    return render(request, 'chess/main/create_configuration.html', {'form': form})


def configuration_board(request, game_type_id):
    game_type = GameType.objects.get(pk=game_type_id)
    chess = Chess(game_type.rules)
    displayable_board = get_displayable_board(chess.board)

    if request.method == "POST":
        form = GameTypeForm(request.POST, instance=game_type)
        if form.is_valid():
            game_type = form.save()
    else:
        form = GameTypeForm(instance=game_type)

    pieces = get_pieces(game_type.rules)

    url = reverse('chess-configuration-configure-board', args=[game_type.id])

    context = {
        'id': game_type.id,
        'form': form,
        'board': displayable_board,
        'black_pieces': pieces['black'],
        'white_pieces': pieces['white'],
        'url': url,
    }
    return render(request, 'chess/main/configure_board.html', context)


def configuration(request, game_type_id):
    game_type = GameType.objects.get(pk=game_type_id)

    if request.method == "POST":
        form = GameTypeForm(request.POST, instance=game_type)
        if form.is_valid():
            game_type = form.save()
    else:
        form = GameTypeForm(instance=game_type)

    directions = get_movement_directions()
    movement_rules = get_movement_rules()
    capture_actions = get_capture_action_rules()
    post_move_actions = get_post_move_actions_rules()
    pieces = get_pieces(game_type.rules)['black']

    checkmark_url = reverse('chess-configuration-checkmark', args=[game_type.id])

    context = {
        'id': game_type.id,
        'checkmark_url': checkmark_url,
        'pieces': pieces,
        'enums': {
            'directions': directions,
            'movements': movement_rules,
            'capture_actions': capture_actions,
            'post_move_actions': post_move_actions,
        },
        'form': form,
    }
    return render(request, 'chess/main/configuration.html', context)

DjangoChessApi/Chess/views/GameListView.py
from django.views.generic.list import ListView

from DjangoChessApi.Chess.models import Game


class GameListView(ListView):

    context_object_name = 'my_games'
    paginate_by = 100  # if pagination is desired
    template_name = "chess/game_list.html"

    def get_queryset(self):
        return Game.objects.filter(player1=self.request.user) | Game.objects.filter(
            player1=self.request.user
        )

DjangoChessApi/Chess/views/UserGameTypeListView.py
from django.views.generic.list import ListView

from DjangoChessApi.Chess.models import GameType


class UserGameTypeListView(ListView):

    context_object_name = 'game_types'
    paginate_by = 100  # if pagination is desired

    def get_queryset(self):
        print(self.request)
        return GameType.objects.filter(created_by=self.request.user)

    def get_template_names(self):
        return ['chess/user_gametype_list.html']

DjangoChessApi/Chess/views/UserListView.py
from django.db.models import Count
from django.utils import timezone
from django.views.generic.list import ListView

from DjangoChessApi.Chess.models import User


class UserListView(ListView):
    model = User
    context_object_name = 'users'
    paginate_by = 100  # if pagination is desired

    def get_template_names(self):
        return ['chess/user_list.html']

    def get_queryset(self):
        return User.objects.annotate(count=Count('gametype__id')).order_by('-count')

DjangoChessApi/Chess/templates/chess/secondary/board.html
{% load get_item %}
{% load times %}
{% load times_reverse %}

<div class="chess_board">
  {% for row in 8|times_reverse %}
    <div class="row">
      {% for column in 8|times %}
        {% with key=""|add:row|add:","|add:column %}
          {% if board|get_item:key|get_item:'promote_me_daddy' %}
            <div class="square promote"
                  data-row={{row}}
                  data-column={{column}}
                  data-name={{board|get_item:key|get_item:'name'}}
                  data-color={{board|get_item:key|get_item:'color'}}
                  id="{{row}},{{column}}">
          {% else %}
            <div class="square" data-row={{row}} data-column={{column}} id="{{row}},{{column}}">
          {% endif %}
            {% if board|get_item:key|get_item:'image' %}
              <img src="{{ board|get_item:key|get_item:'image' }}">
            {% endif %}
          </div>
        {% endwith %}
      {% endfor %}
    </div>
  {% endfor %}
</div>

DjangoChessApi/Chess/templates/chess/secondary/configuration_navbar.html
<nav>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      {% if rules_active %}
        <a class="nav-link active" href={% url 'Chess:configure-edit' id %}>Edit Rules</a>
      {% else %}
        <a class="nav-link" href={% url 'Chess:configure-edit' id %}>Edit Rules</a>
      {% endif %}
    </li>
    <li class="nav-item">
      {% if board_active %}
        <a class="nav-link active" href={% url 'Chess:configure-board' id %}>Edit Starting Positions</a>
      {% else %}
        <a class="nav-link" href={% url 'Chess:configure-board' id %}>Edit Starting Positions</a>
      {% endif %}
    </li>
    <li>
      <a class="nav-link" href={% url 'Chess:create-game-redirect' id %}>Play Game</a>
    </li>
  </ul>
</nav>

DjangoChessApi/Chess/templates/chess/secondary/game_type.html
<div class='card'>
  <div class='card-body'>
    <div class='title'>
      <h4 class="card-title">{{ game_type.name }}</h4>
    </div>
    <div>
      <p>{{ game_type.description }}</p>
    </div>
    <div class="game-type-actions">
      <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Play game
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item" href="{% url 'Chess:create-game-redirect' game_type.id %}?free_play=true">Free Play</a>
          <a class="dropdown-item" href="{% url 'Chess:create-game-redirect' game_type.id %}?free_play=false">Invite Opponent</a>
        </div>
      </div>
      <button data-url={% url 'Chess:configure-edit' game_type.id %}>Edit Rules</button>
      <button data-url={% url 'chess-configuration-detail' game_type.id %} class="delete">Delete Rules</button>
    </div>
  </div>
</div>

DjangoChessApi/Chess/templates/chess/secondary/piece_card.html
<div class='card' data-piece={{piece}} data-color={{color}} data-image={{data.image}}>
  <img class='card-img-top' src={{data.image}} alt={{piece}}>
  <div class='card-body'>
    <div class='title'>
      <h4 class="card-title">{{piece}}</h4>
    </div>
    {% block details %}

    {% endblock %}
  </div>
</div>

DjangoChessApi/Chess/templates/chess/secondary/piece_configuration.html
{% extends 'chess/secondary/piece_card.html' %}
{% load index %}

{% block details %}
<div class='moves'>
  {% for move in data.moves %}
    {% with i=forloop.counter %}
    <div class="movement">
        <h6 class="card-subtitle">Directions {{ forloop.counter }}</h6>
        <div>
          {% for direction in enums.directions %}
            <div class="form-check">
              {% if direction in move.directions %}
                <input data-piece="{{piece}}" data-index="{{i}}" data-key="directions" data-value="{{direction}}" type="checkbox" class="form-check-input" name="{{ piece }}{{ i }}direction" checked>
              {% else %}
                <input data-piece="{{piece}}" data-index="{{i}}" data-key="directions" data-value="{{direction}}" type="checkbox" class="form-check-input" name="{{ piece }}{{ i }}direction">
              {% endif %}
              <label class="form-check-label" for="{{ piece }} {{ direction }}">{{ direction }}</label>
            </div>
          {% endfor %}
        </div>

        <h6 class="card-subtitle">Pre-Move Checks {{ forloop.counter }}</h6>
        <div>
          {% for check in move.pre_move_checks %}
            <div class="d-flex flex-row">
              <div>
                <textarea>{{ check.locations|join:"&#13;&#10;" }}</textarea>
              </div>
              <div class="form-check d-flex flex-column">
                {% for check_definition in enums.pre_move_checks %}
                  {% with j=forloop.counter %}
                    <div>
                      {% if check_definition in check.checks %}
                        <input data-piece="{{piece}}" data-index="{{i}}" data-key="pre_move_checks" data-value="{{check_definition}}" type="checkbox" class="form-check-input checked" name="{{ piece }}{{ i }}{{ j }}{{ check_definition }}" checked>
                      {% else %}
                        <input data-piece="{{piece}}" data-index="{{i}}" data-key="pre_move_checks" data-value="{{check_definition}}" type="checkbox" class="form-check-input" name="{{ piece }}{{ i }}{{ j }}{{ check_definition }}">
                      {% endif %}
                      <label class="form-check-label" for="{{ piece }}{{ i }}{{ j }}{{ check_definition }}">{{ check_definition }}</label>
                    </div>
                  {% endwith %}
                {% endfor %}
              </div>
            </div>
          {% endfor %}
        </div>

        <h6 class="card-subtitle"> Movement Rules {{ forloop.counter }}</h6>
        <div>
          {% for movement in enums.movements %}
            <div class="form-check">
              {% if movement in move.conditions %}
                <input data-piece="{{piece}}" data-index="{{i}}" data-key="conditions" data-value="{{movement}}" type="checkbox" class="form-check-input checked" name="{{ piece }}{{ i }}condition" checked>
              {% else %}
                <input data-piece="{{piece}}" data-index="{{i}}" data-key="conditions" data-value="{{movement}}" type="checkbox" class="form-check-input" name="{{ piece }}{{ i }}condition">
              {% endif %}

              <label class="form-check-label" for="{{ piece }} {{ movement }}">{{ movement }}</label>
            </div>
          {% endfor %}
        </div>

        <h6 class="card-subtitle"> Capture Actions {{ forloop.counter }}</h6>
        <div>
          {% for action in enums.capture_actions %}
            <div class="form-check">
              {% if action in move.capture_actions %}
                <input data-piece="{{piece}}" data-index="{{i}}" data-key="capture_actions" data-value="{{action}}" type="checkbox" class="form-check-input" name="{{ piece }}{{ i }}capture_action" checked>
              {% else %}
                <input data-piece="{{piece}}" data-index="{{i}}" data-key="capture_actions" data-value="{{action}}" type="checkbox" class="form-check-input" name="{{ piece }}{{ i }}capture_action">
              {% endif %}
              <label class="form-check-label" for="{{ piece }} {{ action }}">{{ action }}</label>
            </div>
          {% endfor %}
        </div>

        <h6 class="card-subtitle"> Additional Capture Locations {{ forloop.counter }}</h6>
        <div>
          <textarea class="w-100">{{ move.capture_at|join:"&#13;&#10;" }}</textarea>
        </div>

        <h6 class="card-subtitle"> Post Move Actions {{ forloop.counter }}</h6>
        <div>
          {% for action in enums.post_move_actions %}
            <div class="form-check">
              {% if action in move.post_move_actions %}
                <input data-piece="{{piece}}" data-index="{{i}}" data-key="post_move_actions" data-value="{{action}}" type="checkbox" class="form-check-input" name="{{ piece }}{{ i }}post_move_action" checked>
              {% else %}
                <input data-piece="{{piece}}" data-index="{{i}}" data-key="post_move_actions" data-value="{{action}}" type="checkbox" class="form-check-input" name="{{ piece }}{{ i }}post_move_action">
              {% endif %}
              <label class="form-check-label" for="{{ piece }} {{ action }}">{{ action }}</label>
            </div>
          {% endfor %}
        </div>

        <h6 class="card-subtitle">Side Effects {{ forloop.counter }}</h6>
          <div class="d-flex flex-row">
            <textarea class="w-100">{{ move.side_effects }}</textarea>
          </div>
        </h6>

      </div>

    {% if i|divisibleby:2 %}
      <hr>
    {% endif %}
    {% endwith %}
  {% endfor %}
</div>
{% endblock %}

DjangoChessApi/Chess/templates/chess/secondary/piece_selection.html
{% for color, pieces in promotion_pieces.items %}
  <div id="piece-selection-popover-content-{{color}}" class="d-none">
    {% for piece, data in pieces.items %}
      {% include "chess/secondary/piece_card.html" with piece=piece data=data color=color %}
    {% endfor %}
  </div>
{% endfor %}